name: cover

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"
          cache: true

      - name: ⚙️ Install Tools
        run: ./.github/workflows/scripts/install-tools.sh

      - name: 📦 Install Dependencies
        run: melos bootstrap

      - name: 🧪 Run Tests with Coverage
        run: melos run coverage
      
      - name: 📊 Upload Code Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}